# -*- mode: ruby -*-
# vi:set ft=ruby sw=2 ts=2 sts=2:

NUM_MASTER_NODE = 1
NUM_WORKER_NODE = 2

IP_NW = "192.168.56."
MASTER_IP_START = 11
NODE_IP_START = 12
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  # Disable automatic box update checking.
  config.vm.box_check_update = false
  config.vm.provision "shell", path: "../ubuntu_1.23/initialSetup.sh"

  # Provision Master Nodes
  (1..NUM_MASTER_NODE).each do |i|
      config.vm.define "master230#{i}" do |node|
        node.vm.provider "virtualbox" do |vb|
            vb.name = "master230#{i}"
            vb.memory = 2048
            vb.cpus = 2
        end
        node.vm.hostname = "master230#{i}"
        node.vm.network :private_network, ip: IP_NW + "#{MASTER_IP_START + i}"
        node.vm.network "forwarded_port", guest: 22, host: "#{2710 + i}"
        node.vm.provision "setup-hosts", :type => "shell", :path => "../ubuntu_1.23/setup-hosts.sh" do |s|
          s.args = ["enp0s8"]
        end
        node.vm.provision "setup-dns"       , type: "shell", :path => "../ubuntu_1.23/update-dns.sh"
        node.vm.provision "setup-k8s_master", type: "shell", path: "../ubuntu_1.23/setupmaster.sh"
      end
  end


  # Provision worker nodes
  (1..NUM_WORKER_NODE).each do |i|
    config.vm.define "worker230#{i}" do |node|
        node.vm.provider "virtualbox" do |vb|
            vb.name = "worker230#{i}"
            vb.memory = 1024
            vb.cpus = 1
        end
        node.vm.hostname = "worker230#{i}"
        node.vm.network :private_network, ip: IP_NW + "#{NODE_IP_START + i}"
        node.vm.network "forwarded_port", guest: 22, host: "#{2720 + i}"
        node.vm.provision "setup-hosts", :type => "shell", :path => "../ubuntu_1.23/setup-hosts.sh" do |s|
          s.args = ["enp0s8"]
        end
        node.vm.provision "setup-dns", type: "shell", :path => "../ubuntu_1.23/update-dns.sh"
        node.vm.provision "setup-k8s_worker", type: "shell", :path => "../ubuntu_1.23/setupworker.sh"
    end
  end
end
