# -*- mode: ruby -*-
# vi:set ft=ruby sw=2 ts=2 sts=2:

NUM_MASTER_NODE = 1
NUM_WORKER_NODE = 1 

#IP_NW = "192.168.56."
MASTER_IP_START = 1
NODE_IP_START = 1
Vagrant.configure("2") do |config|
  config.vm.boot_timeout = 720
  config.vm.box = "ubuntu/jammy64"
  # Disable automatic box update checking.
  config.vm.box_check_update = false
  config.vm.provision "shell", path: "ubuntu_1.2x/initialSetup_containerd.sh"
  config.vm.provision "file", source: "ubuntu_1.2x/netplan_template", destination: "/var/tmp/netplan_template"
  config.vm.provision "file", source: "ubuntu_1.2x/keys", destination: "/var/tmp/keys"
  config.vm.provision "file", source: "ubuntu_1.2x/flannel", destination: "/var/tmp/flannel"

  BRIDGE_ADAPTER = "wlp2s0"

#
  def pinned_mac(id)
    base_prefix = "080027DEAD"
    last_byte = format('%02X', id) 
    "#{base_prefix}#{last_byte}"
  end 
#
  # Provision Master Nodes
  (1..NUM_MASTER_NODE).each do |i|
      config.vm.define "ckamaster0#{i}" do |node|
        node.vm.provider "virtualbox" do |vb|
            vb.name   = "ckamaster0#{i}"
            vb.memory = 2048
            vb.cpus   = 2
            vb.customize ["modifyvm", :id, "--macaddress2", pinned_mac(i)]
        end

      # Bridged = DHCP from your router (10.20.x.x)

        node.vm.hostname = "ckamaster0#{i}"
#
#        node.vm.network :private_network, ip: IP_NW + "#{MASTER_IP_START + i + 50}"
        node.vm.network "public_network", bridge: BRIDGE_ADAPTER, use_dhcp_assigned_default_route: true
        node.vm.network "forwarded_port", guest: 22, host: 6223
        node.vm.provision "setup-hosts", :type => "shell", :path => "ubuntu_1.2x/setup-hosts.sh" do |s|
        end
        node.vm.provision "setup-dns"       , type: "shell", :path => "ubuntu_1.2x/update-dns.sh"
        node.vm.provision "setup-k8s_master", type: "shell", path: "ubuntu_1.2x/setupmaster.sh"
      end
  end


  # Provision worker nodes
  (1..NUM_WORKER_NODE).each do |i|
    config.vm.define "ckaworker0#{i}" do |node|
        node.vm.provider "virtualbox" do |vb|
            vb.name = "ckaworker0#{i}"
            vb.memory = 1024
            vb.cpus = 1
            vb.customize ["modifyvm", :id, "--macaddress2", pinned_mac(i+1)]
        end
        node.vm.hostname = "ckaworker0#{i}"
#        node.vm.network :private_network, auto_config: false, ip: IP_NW + "#{NODE_IP_START + i + 50}"
        node.vm.network "public_network", bridge: BRIDGE_ADAPTER, use_dhcp_assigned_default_route: true
        node.vm.network "forwarded_port", guest: 22, host: 6232, auto_correct: true
        node.vm.provision "setup-hosts", :type => "shell", :path => "ubuntu_1.2x/setup-hosts.sh" do |s|
          s.args = ["enp0s8"]
        end
        node.vm.provision "setup-dns", type: "shell", :path => "ubuntu_1.2x/update-dns.sh"
# this is used only if subnet 192.168.56 is used
#        node.vm.provision "config-net", type: "shell", :path => "ubuntu_1.2x/netconfig.sh"
        node.vm.provision "setup-k8s_worker", type: "shell", :path => "ubuntu_1.2x/setupworker.sh"
    end
  end
end
