# -*- mode: ruby -*-
# vi:set ft=ruby sw=2 ts=2 sts=2:

NUM_MASTER_NODE = 1
NUM_WORKER_NODE = 2

IP_NW = "192.168.56."
MASTER_IP_START = 1
NODE_IP_START = 2
Vagrant.configure("2") do |config|
  config.vm.boot_timeout = 720
  config.vm.box = "ubuntu/focal64"
  # Disable automatic box update checking.
  config.vm.box_check_update = false
  config.vm.provision "shell", path: "../ubuntu_1.24/initialSetup_containerd.sh"

  # Provision Master Nodes
  (1..NUM_MASTER_NODE).each do |i|
      config.vm.define "master0#{i}" do |node|
        node.vm.provider "virtualbox" do |vb|
            vb.name = "master0#{i}"
            vb.memory = 2048
            vb.cpus = 2
        end
        node.vm.hostname = "master0#{i}"
        node.vm.network :private_network, ip: IP_NW + "#{MASTER_IP_START + i}"
        node.vm.network "forwarded_port", guest: 22, host: 2222
        node.vm.provision "setup-hosts", :type => "shell", :path => "../ubuntu_1.24/setup-hosts.sh" do |s|
          s.args = ["enp0s8"]
        end
        node.vm.provision "setup-dns"       , type: "shell", :path => "../ubuntu_1.24/update-dns.sh"
        node.vm.provision "setup-k8s_master", type: "shell", path: "../ubuntu_1.24/setupmaster.sh"
      end
  end


  # Provision worker nodes
  (1..NUM_WORKER_NODE).each do |i|
    config.vm.define "worker0#{i}" do |node|
        node.vm.provider "virtualbox" do |vb|
            vb.name = "worker0#{i}"
            vb.memory = 1024
            vb.cpus = 1
        end
        node.vm.hostname = "worker0#{i}"
        node.vm.network :private_network, ip: IP_NW + "#{NODE_IP_START + i}"
        node.vm.network "forwarded_port", guest: 22, host: "#{2200 + i}", auto_correct: true
        node.vm.provision "setup-hosts", :type => "shell", :path => "../ubuntu_1.24/setup-hosts.sh" do |s|
          s.args = ["enp0s8"]
        end
        node.vm.provision "setup-dns", type: "shell", :path => "../ubuntu_1.24/update-dns.sh"
        node.vm.provision "setup-k8s_worker", type: "shell", :path => "../ubuntu_1.24/setupworker.sh"
    end
  end
end
